pterodactyl_env:
  app_url: "http://192.168.65.161/panel"
  app_timezone: "UTC"
  cache_driver: "redis"
  session_driver: "redis"
  queue_driver: "redis"
  redis_host: "127.0.0.1"
  redis_port: "6379"
  enable_ui: "yes"
  telemetry: "no"
  egg_author_email: "caldur33@gmail.com"
  db_host: "127.0.0.1"
  db_port: "3306"
  db_database: "panel"
  db_username: "pterodactyl"
  db_password: "123456"
